name: Upload Python Package via Poetry

on:
  release:
    types: [published]
  # if debug
  workflow_dispatch:

jobs:
  deploy:
    # if debug, commented out
    # if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-dynamic-versioning
    - name: Poetry settings
      run: |
        poetry self add "poetry-dynamic-versioning[plugin]"
        poetry dynamic-versioning enable
        poetry config repositories.testpypi https://test.pypi.org/legacy/
    - name: Build and publish
      run: |
        poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
